In [868]:
import numpy as np
import random

In [869]:
l = 40
n = 512

# Generate

In [870]:
def Generate(n, l):
    arr = np.random.randint(2, size = (n, l))
    return arr

In [871]:
parents = Generate(n, l)
parents

array([[0, 1, 0, ..., 0, 1, 1],
       [0, 0, 1, ..., 0, 0, 1],
       [1, 0, 1, ..., 1, 1, 1],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 1],
       [1, 0, 1, ..., 1, 1, 1]])

## Crossover

In [872]:
def Uniform_Crossover(parents, n, l):
    i = 0
    offspring = parents.copy()
    while (i < n - 1):
        for j in range(0, l):
            if (random.uniform(0, 1) < 0.5):
                tm = offspring[i][j]
                offspring[i][j] = offspring[i + 1][j]
                offspring[i + 1][j] = tm
        i += 2
    return offspring

In [873]:
def Onepoint_Crossover(parents, n, l):
    offspring = parents.copy()
    i = 0
    while (i < n - 1):
        k = random.randint(1, l - 2)
        for j in range(k, l):
            tm = offspring[i][j]
            offspring[i][j] = offspring[i + 1][j]
            offspring[i + 1][j] = tm
        i += 2
    return offspring

## Check Convergence

In [874]:
def Compare_2_Individual(p1, p2):
    for i in range(l):
        if (p1[i] != p2[i]):
            return False
    return True

In [875]:
def Check_Convergence(n):
    for i in range(n - 1):
        if (Compare_2_Individual(parents[i], parents[i + 1]) == False):
            return False
    return True

## Shuffle

In [876]:
def Pool(parents, offspring):
    return np.vstack((parents, offspring))

In [877]:
def Onemax(arr):
    s = 0
    for i in arr:
        s += i
    return s

In [878]:
def Trap5(arr):
    s = 0
    for i in arr:
        s += i
    if s == 5: 
        return 5
    return 4 - s;

In [879]:
def Concatenated_Trap5(arr): 
    arr2 = []
    s = 0
    for i in range(len(arr)):
        if (i + 1) % 5 != 0:
            arr2.append(arr[i])
        else:
            arr2.append(arr[i])
            s += Trap5(arr2)
            arr2 = []
    return s

In [880]:
def Shuffle(n):
    arr = np.arange(2 * n)
    np.random.shuffle(arr)
    return arr

## Selection

In [881]:
def TournamentSelection(parents, fitness_parents, pool, fitness_pool, n):
    cnt = -1
    for k in range(2):
        si = np.arange(2 * n)
        np.random.shuffle(si)
        max_fitness = 0
        max_index = -1
 
        for i in range(2 * n):
            if (i % 4 == 3):
                cnt += 1
                parents[cnt] = pool[max_index]
                fitness_parents[cnt] = fitness_pool[max_index]
                max_fitness = 0
                max_index = -1
            else:
                if (fitness_pool[si[i]] >= max_fitness):
                    max_fitness = fitness_pool[si[i]]
                    max_index = si[i]
    return parents

## Main

In [882]:
print (parents)
print('')
while (Check_Convergence(n) == False):
    offspring = Onepoint_Crossover(parents, n, l)
    pool = Pool(parents, offspring)
    
    fitness_parents = []
    for i in range(n):
       # fitness_parents.append(Onemax(parents[i]))
        fitness_parents.append(Concatenated_Trap5(parents[i]))
        
    fitness_offspring = []
    for i in range(n):
        #fitness_offspring.append(Onemax(offspring[i]))
        fitness_offspring.append(Concatenated_Trap5(offspring[i]))
        
    fitness_pool = fitness_parents.copy()
    for i in range (n):
        fitness_pool.append(fitness_offspring[i])
    
    parents = TournamentSelection(parents, fitness_parents, pool, fitness_pool, n)
    #print (parents)

[[0 1 0 ... 0 1 1]
 [0 0 1 ... 0 0 1]
 [1 0 1 ... 1 1 1]
 ...
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 1]
 [1 0 1 ... 1 1 1]]



## Result

In [883]:
for i in range(n):
    print(parents[i], end =' ')
    print(fitness_parents[i])

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1] 40
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1] 40
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1] 40
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1] 40
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1] 40
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1] 40
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1] 40
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1] 40
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1] 40
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1] 40
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1] 40
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1